package com.scoova.ride

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import androidx.compose.ui.unit.LayoutDirection

/**
 * App UI string table.
 *
 * Keeps user-visible UI strings (button labels, section titles, hints,
 * empty-state messages, …) separate from server-rendered nav copy.
 * Nav phrases live on the server in `trip.scoova.state.*` — those don't
 * belong here.
 *
 * Lookup:
 * ```kotlin
 * Text(Strings.t("settings.title", settings.locale))
 * ```
 *
 * Falls back to `en` when the requested locale isn't translated yet, and
 * to the key itself when the string isn't defined. That way a missing
 * translation is loud (you see `settings.foo` on screen) instead of
 * silently broken.
 */
object Strings {
    private val tables: Map<String, Map<String, String>> = mapOf(
        "en" to mapOf(
            // Tabs
            "tab.map" to "Map",
            "tab.history" to "History",
            "tab.insights" to "Insights",
            "tab.settings" to "Settings",
            // Greetings (BrandGreeting in PlanScreen)
            "greeting.morning" to "Good morning",
            "greeting.afternoon" to "Good afternoon",
            "greeting.evening" to "Good evening",
            "greeting.lateride" to "Late ride?",
            // Search pill
            "search.placeholder" to "Where to?",
            "search.empty" to "No results. Long-press the map to drop a pin instead.",
            "search.searching" to "Searching…",
            // Home / Work chips
            "place.home.set" to "Set Home",
            "place.work.set" to "Set Work",
            "place.home" to "Home",
            "place.work" to "Work",
            // Set-place wizard
            "wizard.home.title" to "Set your home",
            "wizard.work.title" to "Set your work",
            "wizard.subtitle" to "Where should we route you when you tap {label}?",
            "wizard.search" to "Search address",
            "wizard.or" to "  OR  ",
            "wizard.use_location" to "Use my current location",
            "wizard.waiting_gps" to "Waiting for GPS fix…",
            "wizard.pick_on_map" to "Pick on the map",
            // Pin-drop banner
            "pindrop.title" to "Drop a pin for {label}",
            "pindrop.body" to "Long-press anywhere on the map.",
            "pindrop.cancel" to "Cancel",
            // Route preview / ride
            "route.start" to "Start ride",
            "route.simulate" to "Simulate",
            "route.cancel" to "Cancel route",
            "ride.speed" to "SPEED",
            "ride.covered" to "COVERED",
            "ride.eta" to "ETA",
            "ride.end" to "End ride",
            // Summary
            "summary.title" to "Ride summary",
            "summary.distance" to "Distance",
            "summary.duration" to "Duration",
            "summary.avg_speed" to "Avg speed",
            "summary.plan_another" to "Plan another",
            // Settings
            "settings.title" to "Settings",
            "settings.profile" to "YOUR PROFILE",
            "settings.profile.change" to "Change",
            "settings.units" to "UNITS",
            "settings.units.metric" to "Metric (km, m, km/h, °C)",
            "settings.units.imperial" to "Imperial (mi, ft, mph, °F)",
            "settings.language" to "LANGUAGE",
            "settings.language.description" to "Voice cues + app UI. Switch any time — Scoova ships dialect-aware phrasing in 7.",
            "settings.voice" to "VOICE",
            "settings.voice.speak" to "Speak turn cues",
            "settings.voice.speak.desc" to "Turn-by-turn voice with phase-aware phrasing.",
            "settings.voice.spatial" to "Spatial audio",
            "settings.voice.spatial.desc" to "Left-turn cues play in your left ear, right in your right. Earbuds recommended.",
            "settings.voice.test" to "Test spatial audio",
            "settings.voice.test.desc" to "Plays a left tone, then a right. Make sure earbuds are on.",
            "settings.voice.test.cta" to "PLAY",
            "settings.about" to "ABOUT",
            "settings.about.tagline" to "Scoova Ride · v1.0 · Eye-on-Road navigation",
            // About card
            "about.title" to "What is Scoova?",
            "about.body" to "Scoova is a navigation layer built for riders, not drivers. We strip distractions, speak in your dialect, and call out landmarks you can actually see from the road.",
            "about.bullet1" to "Eyes-on-road copy — short verbs, real landmarks",
            "about.bullet2" to "7 languages including Egyptian Arabic",
            "about.bullet3" to "Spatial audio cues — left turn in your left ear",
            "about.bullet4" to "Sensor-fused turn confirmation and drift detection",
            "about.bullet5" to "All phrasing server-side — instant updates, zero app release",
            // Profiles (6 movers)
            "profile.walker.display" to "Walker",
            "profile.walker.tagline" to "Calm cues. Sidewalk routes.",
            "profile.runner.display" to "Runner",
            "profile.runner.tagline" to "Cheerful pace. Distance focus.",
            "profile.cyclist.display" to "Cyclist",
            "profile.cyclist.tagline" to "Bike routes. Mid-range cues.",
            "profile.scooter.display" to "Scooter",
            "profile.scooter.tagline" to "Scooter pace. Curb-aware.",
            "profile.driver.display" to "Driver",
            "profile.driver.tagline" to "Highway speeds. Eyes up.",
            "profile.courier.display" to "Courier",
            "profile.courier.tagline" to "Delivery loops. Tight cues.",
            // Persona picker
            "persona.title" to "How are you moving?",
            "persona.subtitle" to "Scoova adapts its cues, pace, and routing to how you ride.",
            "persona.continue" to "Continue",
            // History
            "history.title" to "Ride history",
            "history.count" to "{n} rides",
            "history.empty.title" to "No rides yet",
            "history.empty.body" to "Your first ride will appear here, with distance, time and average speed.",
            "history.row.distance" to "{km} km",
            "history.row.duration" to "{min} min",
            "history.total_distance" to "TOTAL DISTANCE",
            "history.total_time" to "TOTAL TIME",
            "history.rides_label" to "RIDES",
            "history.avg" to "{kph} km/h avg",
            // Insights
            "insights.title" to "Insights",
            "insights.subtitle" to "How your eyes stayed on the road",
            "insights.empty.title" to "No data yet",
            "insights.empty.body" to "Complete a ride to see your eyes-up score, cue stats, audio route mix, and lifetime totals.",
            "insights.total_distance" to "Total distance",
            "insights.total_rides" to "Rides",
            "insights.avg_speed" to "Avg speed",
            "insights.by_profile" to "BY PROFILE",
            "insights.weekly" to "WEEKLY",
            "insights.last_7_days" to "LAST 7 DAYS",
            "insights.eor" to "EYE-ON-ROAD",
            "insights.last_ride" to "LAST RIDE",
            "insights.avg" to "AVG",
            "insights.time" to "TIME",
            "insights.min" to "min",
            "insights.profile" to "PROFILE",
            "insights.lifetime_km" to "LIFETIME KM",
            "insights.lifetime_min" to "LIFETIME MIN",
            "insights.7d_ago" to "7d ago",
            "insights.today" to "Today",
            "insights.total_km" to "Total: {km} km",
            "insights.soon" to "SOON",
            "insights.eyes_up.title" to "Eyes-up score",
            "insights.eyes_up.desc" to "% of ride with the screen off and untouched.",
            "insights.audio_mix.title" to "Audio route mix",
            "insights.audio_mix.desc" to "Bluetooth · wired · phone · car — over the last 30 days.",
            "insights.cue_latency.title" to "Cue latency P50 / P95",
            "insights.cue_latency.desc" to "Threshold-cross to TTS-start. Health check on the voice path.",
            "insights.landmark_vs_metric.title" to "Landmark vs metric cues",
            "insights.landmark_vs_metric.desc" to "Quality of phrasing — did we say at the mosque, or just in 247 m?",
            // Summary
            "summary.complete" to "Ride complete",
            "summary.unit_km" to "km covered",
            "summary.unit_min" to "min in saddle",
            "summary.unit_kmh" to "km/h average",
            "summary.unit_mi" to "mi covered",
            "summary.unit_mph" to "mph average",
            "summary.plan_another_cta" to "Plan another ride",
            "summary.fallback_label" to "Ride",
            // Onboarding
            "onboarding.skip" to "Skip",
            "onboarding.next" to "Next",
            "onboarding.start" to "Get started",
            "onboarding.p1.title" to "Eyes on the road,\nnot on the screen",
            "onboarding.p1.body" to "Scoova talks in landmarks the way locals do — 'third exit at the square', 'after the mosque' — so you can navigate without looking down.",
            "onboarding.p1.demo.phase" to "NEXT",
            "onboarding.p1.demo.verb" to "Third exit",
            "onboarding.p1.demo.anchor" to "at Tahrir Square, onto Ramsis Street",
            "onboarding.p2.title" to "Your dialect,\nyour way",
            "onboarding.p2.body" to "Cues in 7 languages — Egyptian Arabic, MSA, English, French, German, Spanish, Turkish. The tone matches how riders actually talk.",
            "onboarding.p3.title" to "Adapts to\nhow you move",
            "onboarding.p3.body" to "Walker, runner, cyclist, scooter, driver, courier. Scoova picks the route, timing, and tone that fit how you ride — switch per trip.",
            // Settings → re-show tour
            "settings.replay_tour" to "How does Scoova work?",
            "settings.replay_tour.desc" to "Replay the value-props tour any time.",
            "settings.take_tour" to "Take a tour",
            "settings.take_tour.desc" to "A prepared ride with voice cues and callouts that explain each feature as it happens.",
        ),
        "ar-EG" to mapOf(
            "tab.map" to "الخريطة",
            "tab.history" to "السجل",
            "tab.insights" to "إحصائيات",
            "tab.settings" to "الإعدادات",
            "greeting.morning" to "صباح الخير",
            "greeting.afternoon" to "ظهيرة سعيدة",
            "greeting.evening" to "مساء الخير",
            "greeting.lateride" to "رحلة متأخرة؟",
            "search.placeholder" to "هتروح فين؟",
            "search.empty" to "مفيش نتائج. اضغط مطول على الخريطة عشان تحط دبوس.",
            "search.searching" to "بدور…",
            "place.home.set" to "حدد البيت",
            "place.work.set" to "حدد الشغل",
            "place.home" to "البيت",
            "place.work" to "الشغل",
            "wizard.home.title" to "حدد البيت",
            "wizard.work.title" to "حدد الشغل",
            "wizard.subtitle" to "لما تختار {label}، سكوفا توديك فين؟",
            "wizard.search" to "ابحث عن عنوان",
            "wizard.or" to "  أو  ",
            "wizard.use_location" to "استخدم موقعي دلوقتي",
            "wizard.waiting_gps" to "في انتظار GPS…",
            "wizard.pick_on_map" to "اختار من الخريطة",
            "pindrop.title" to "حط دبوس لـ {label}",
            "pindrop.body" to "اضغط مطول في أي مكان على الخريطة.",
            "pindrop.cancel" to "إلغاء",
            "route.start" to "ابدأ الرحلة",
            "route.simulate" to "محاكاة",
            "route.cancel" to "إلغاء الطريق",
            "ride.speed" to "السرعة",
            "ride.covered" to "المسافة",
            "ride.eta" to "الوصول",
            "ride.end" to "إنهاء",
            "summary.title" to "ملخص الرحلة",
            "summary.distance" to "المسافة",
            "summary.duration" to "المدة",
            "summary.avg_speed" to "متوسط السرعة",
            "summary.plan_another" to "خطط رحلة تانية",
            "settings.title" to "الإعدادات",
            "settings.profile" to "حسابك",
            "settings.profile.change" to "تغيير",
            "settings.units" to "الوحدات",
            "settings.units.metric" to "متري (كم، م، كم/س، °م)",
            "settings.units.imperial" to "إمبريالي (ميل، قدم، م/س، °ف)",
            "settings.language" to "اللغة",
            "settings.language.description" to "لغة الصوت وواجهة التطبيق. غيّر في أي وقت — سكوفا تتكلم 7 لهجات.",
            "settings.voice" to "الصوت",
            "settings.voice.speak" to "نطق التعليمات",
            "settings.voice.speak.desc" to "صوت التوجيه خطوة بخطوة مع تعبيرات اللهجة.",
            "settings.voice.spatial" to "صوت مكاني",
            "settings.voice.spatial.desc" to "تعليمات الشمال في أذنك الشمال، واليمين في اليمين. استخدم السماعات.",
            "settings.voice.test" to "اختبار الصوت المكاني",
            "settings.voice.test.desc" to "بيشغل نغمة شمال ثم يمين. تأكد من السماعات.",
            "settings.voice.test.cta" to "تشغيل",
            "settings.about" to "عن التطبيق",
            "settings.about.tagline" to "سكوفا رايد · v1.0 · ملاحة بأسلوب Eye-on-Road",
            "about.title" to "إيه هي سكوفا؟",
            "about.body" to "سكوفا طبقة ملاحة معمولة للراكب مش للسائق. بنشيل التشتيت، بنتكلم بلهجتك، وبنذكر معالم تشوفها فعلًا من على الطريق.",
            "about.bullet1" to "كلام مختصر — أفعال قصيرة ومعالم حقيقية",
            "about.bullet2" to "7 لغات منها المصري",
            "about.bullet3" to "صوت مكاني — لفة شمال في أذنك الشمال",
            "about.bullet4" to "تأكيد اللفات من حساسات التليفون وكشف الانحراف",
            "about.bullet5" to "كل الكلام من السيرفر — تحديث فوري، من غير تحديث للتطبيق",
            "profile.walker.display" to "ماشي",
            "profile.walker.tagline" to "صوت هادي. مسار رصيف.",
            "profile.runner.display" to "بيجري",
            "profile.runner.tagline" to "إيقاع مرح. تركيز على المسافة.",
            "profile.cyclist.display" to "بيعجل",
            "profile.cyclist.tagline" to "مسارات عجل. توجيه متوسط المدى.",
            "profile.scooter.display" to "سكوتر",
            "profile.scooter.tagline" to "سرعة سكوتر. حاسس بالرصيف.",
            "profile.driver.display" to "سواق",
            "profile.driver.tagline" to "سرعات طريق سريع. عينيك على الطريق.",
            "profile.courier.display" to "ديليفري",
            "profile.courier.tagline" to "لفات توصيل. توجيه سريع.",
            "persona.title" to "بتتحرك إزاي؟",
            "persona.subtitle" to "سكوفا بتعدل التوجيه والسرعة والمسار حسب طريقتك.",
            "persona.continue" to "كمل",
            "history.title" to "سجل الرحلات",
            "history.count" to "{n} رحلة",
            "history.empty.title" to "ولا رحلة لسه",
            "history.empty.body" to "أول رحلة هتبان هنا — بالمسافة والوقت ومتوسط السرعة.",
            "history.row.distance" to "{km} كم",
            "history.row.duration" to "{min} دقيقة",
            "history.total_distance" to "إجمالي المسافة",
            "history.total_time" to "الوقت الكلي",
            "history.rides_label" to "الرحلات",
            "history.avg" to "{kph} كم/س متوسط",
            "insights.title" to "إحصائيات",
            "insights.subtitle" to "إزاي عيونك فضلت ع الطريق",
            "insights.empty.title" to "مفيش بيانات لسه",
            "insights.empty.body" to "خلّص رحلة وسكوفا هتورّيك سكور العيون وإحصائيات التعليمات وتوزيع الصوت وإجمالي الكيلومترات.",
            "insights.total_distance" to "إجمالي المسافة",
            "insights.total_rides" to "الرحلات",
            "insights.avg_speed" to "متوسط السرعة",
            "insights.by_profile" to "حسب الدور",
            "insights.weekly" to "أسبوعيًا",
            "insights.last_7_days" to "آخر 7 أيام",
            "insights.eor" to "تركيز الطريق",
            "insights.last_ride" to "آخر رحلة",
            "insights.avg" to "المتوسط",
            "insights.time" to "الوقت",
            "insights.min" to "دقيقة",
            "insights.profile" to "الدور",
            "insights.lifetime_km" to "كم إجمالي",
            "insights.lifetime_min" to "دقيقة إجمالي",
            "insights.7d_ago" to "من 7 أيام",
            "insights.today" to "النهاردة",
            "insights.total_km" to "الإجمالي: {km} كم",
            "insights.soon" to "قريب",
            "insights.eyes_up.title" to "سكور العيون على الطريق",
            "insights.eyes_up.desc" to "النسبة اللي عينك كانت بعيدة عن الشاشة فيها.",
            "insights.audio_mix.title" to "توزيع الصوت",
            "insights.audio_mix.desc" to "بلوتوث · سماعات · تليفون · عربية — آخر 30 يوم.",
            "insights.cue_latency.title" to "زمن استجابة التعليمات P50 / P95",
            "insights.cue_latency.desc" to "من عبور الحد الفاصل لبداية الصوت. فحص صحة مسار الصوت.",
            "insights.landmark_vs_metric.title" to "معالم بدل أرقام",
            "insights.landmark_vs_metric.desc" to "جودة الكلام — قلنا عند الجامع، ولا بس بعد 247 متر؟",
            "summary.complete" to "خلصنا الرحلة",
            "summary.unit_km" to "كم اتقطع",
            "summary.unit_min" to "دقيقة",
            "summary.unit_kmh" to "كم/س متوسط",
            "summary.unit_mi" to "ميل اتقطع",
            "summary.unit_mph" to "ميل/س متوسط",
            "summary.plan_another_cta" to "خطط رحلة تانية",
            "summary.fallback_label" to "رحلة",
            "onboarding.skip" to "تخطي",
            "onboarding.next" to "التالي",
            "onboarding.start" to "يلا نبدأ",
            "onboarding.p1.title" to "عينك ع الطريق\nمش ع الشاشة",
            "onboarding.p1.body" to "سكوفا بتكلمك بمعالم زي ما الناس بتقول — 'المخرج التالت في الميدان'، 'بعد الجامع' — عشان تمشي من غير ما تبص ع الشاشة.",
            "onboarding.p1.demo.phase" to "الجاي",
            "onboarding.p1.demo.verb" to "المخرج التالت",
            "onboarding.p1.demo.anchor" to "في ميدان التحرير، ع شارع رمسيس",
            "onboarding.p2.title" to "بلهجتك انت\nمش بأي كلام",
            "onboarding.p2.body" to "تعليمات بـ 7 لغات — مصري، عربي فصحى، إنجليزي، فرنساوي، ألماني، إسباني، تركي. النغمة زي ما الناس بتتكلم بجد.",
            "onboarding.p3.title" to "بتفهم انت بتتحرك\nإزاي",
            "onboarding.p3.body" to "ماشي، بيجري، بيعجل، سكوتر، سواق، ديليفري. سكوفا بتختار المسار والتوقيت والنغمة اللي بتلاقي ركبتك — وتقدر تغير من رحلة للتانية.",
            "settings.replay_tour" to "سكوفا بتشتغل إزاي؟",
            "settings.replay_tour.desc" to "اعرض الجولة التعريفية تاني.",
        ),
        "ar" to mapOf(
            "tab.map" to "الخريطة",
            "tab.history" to "السجل",
            "tab.insights" to "إحصائيات",
            "tab.settings" to "الإعدادات",
            "greeting.morning" to "صباح الخير",
            "greeting.afternoon" to "نهارك سعيد",
            "greeting.evening" to "مساء الخير",
            "greeting.lateride" to "رحلة متأخرة؟",
            "search.placeholder" to "إلى أين؟",
            "place.home.set" to "تحديد المنزل",
            "place.work.set" to "تحديد العمل",
            "place.home" to "المنزل",
            "place.work" to "العمل",
            "wizard.home.title" to "تحديد المنزل",
            "wizard.work.title" to "تحديد العمل",
            "wizard.subtitle" to "عند الضغط على {label}، إلى أين توجهك سكوفا؟",
            "wizard.search" to "ابحث عن عنوان",
            "wizard.or" to "  أو  ",
            "wizard.use_location" to "استخدم موقعي الحالي",
            "wizard.waiting_gps" to "في انتظار إشارة GPS…",
            "wizard.pick_on_map" to "اختر من الخريطة",
            "pindrop.title" to "ضع علامة لـ {label}",
            "pindrop.body" to "اضغط مطولا في أي مكان على الخريطة.",
            "pindrop.cancel" to "إلغاء",
            "route.start" to "ابدأ الرحلة",
            "route.simulate" to "محاكاة",
            "route.cancel" to "إلغاء",
            "ride.speed" to "السرعة",
            "ride.covered" to "المسافة",
            "ride.eta" to "الوصول",
            "ride.end" to "إنهاء",
            "summary.title" to "ملخص الرحلة",
            "summary.distance" to "المسافة",
            "summary.duration" to "المدة",
            "summary.avg_speed" to "متوسط السرعة",
            "summary.plan_another" to "رحلة جديدة",
            "settings.title" to "الإعدادات",
            "settings.profile" to "ملفك",
            "settings.profile.change" to "تغيير",
            "settings.units" to "الوحدات",
            "settings.units.metric" to "متري (كم، م، كم/س، °م)",
            "settings.units.imperial" to "إمبريالي (ميل، قدم، م/س، °ف)",
            "settings.language" to "اللغة",
            "settings.language.description" to "لغة الصوت والواجهة. يمكن التبديل في أي وقت.",
            "settings.voice" to "الصوت",
            "settings.voice.speak" to "نطق التعليمات",
            "settings.voice.speak.desc" to "توجيه صوتي خطوة بخطوة بلهجتك.",
            "settings.voice.spatial" to "صوت مكاني",
            "settings.voice.spatial.desc" to "تعليمات اليسار في أذنك اليسرى، واليمين في اليمنى.",
            "settings.voice.test" to "اختبار الصوت المكاني",
            "settings.voice.test.desc" to "تشغيل نغمة يسار ثم يمين. تأكد من السماعات.",
            "settings.voice.test.cta" to "تشغيل",
            "settings.about" to "عن التطبيق",
            "settings.about.tagline" to "سكوفا رايد · v1.0 · ملاحة Eye-on-Road",
            "about.title" to "ما هي سكوفا؟",
            "about.body" to "سكوفا طبقة ملاحة مصممة للراكب لا للسائق. نزيل المشتتات، نتحدث بلهجتك، ونذكر معالم تراها من الطريق.",
            "about.bullet1" to "نص قصير — أفعال موجزة ومعالم حقيقية",
            "about.bullet2" to "7 لغات تشمل العربية المصرية",
            "about.bullet3" to "صوت مكاني — لفة يسار في أذنك اليسرى",
            "about.bullet4" to "تأكيد اللفات من الحساسات وكشف الانحراف",
            "about.bullet5" to "كل النصوص من الخادم — تحديث فوري دون تحديث التطبيق",
            "profile.walker.display" to "مشاة",
            "profile.walker.tagline" to "تعليمات هادئة. مسارات الرصيف.",
            "profile.runner.display" to "عدّاء",
            "profile.runner.tagline" to "إيقاع مرح. تركيز على المسافة.",
            "profile.cyclist.display" to "دراج",
            "profile.cyclist.tagline" to "مسارات الدراجة. تعليمات متوسطة.",
            "profile.scooter.display" to "سكوتر",
            "profile.scooter.tagline" to "سرعة السكوتر. وعي بالرصيف.",
            "profile.driver.display" to "سائق",
            "profile.driver.tagline" to "سرعات طريق. عيناك على الطريق.",
            "profile.courier.display" to "مراسل",
            "profile.courier.tagline" to "جولات توصيل. تعليمات سريعة.",
            "persona.title" to "كيف تتنقل؟",
            "persona.subtitle" to "سكوفا تكيّف تعليماتها وسرعتها ومساراتها مع طريقتك.",
            "persona.continue" to "متابعة",
            "history.title" to "سجل الرحلات",
            "history.count" to "{n} رحلة",
            "history.empty.title" to "لا رحلات بعد",
            "history.empty.body" to "ستظهر أول رحلة هنا — بالمسافة والوقت ومتوسط السرعة.",
            "history.row.distance" to "{km} كم",
            "history.row.duration" to "{min} دقيقة",
            "history.total_distance" to "إجمالي المسافة",
            "history.total_time" to "الوقت الكلي",
            "history.rides_label" to "الرحلات",
            "history.avg" to "{kph} كم/س متوسط",
            "insights.title" to "إحصائيات",
            "insights.subtitle" to "كيف بقيت عيناك على الطريق",
            "insights.empty.title" to "لا بيانات بعد",
            "insights.empty.body" to "أكمل رحلة لرؤية مؤشر العيون وإحصاءات التعليمات وتوزيع الصوت والإجماليات.",
            "insights.total_distance" to "إجمالي المسافة",
            "insights.total_rides" to "الرحلات",
            "insights.avg_speed" to "متوسط السرعة",
            "insights.by_profile" to "حسب الدور",
            "insights.weekly" to "أسبوعيًا",
            "insights.last_7_days" to "آخر 7 أيام",
            "insights.eor" to "العين على الطريق",
            "insights.last_ride" to "آخر رحلة",
            "insights.avg" to "المتوسط",
            "insights.time" to "الوقت",
            "insights.min" to "دقيقة",
            "insights.profile" to "الدور",
            "insights.lifetime_km" to "كم إجمالي",
            "insights.lifetime_min" to "دقيقة إجمالي",
            "insights.7d_ago" to "منذ 7 أيام",
            "insights.today" to "اليوم",
            "insights.total_km" to "الإجمالي: {km} كم",
            "insights.soon" to "قريبا",
            "insights.eyes_up.title" to "مؤشر العيون على الطريق",
            "insights.eyes_up.desc" to "النسبة من الرحلة بشاشة مغلقة وغير ممسوسة.",
            "insights.audio_mix.title" to "توزيع الصوت",
            "insights.audio_mix.desc" to "بلوتوث · سلكي · هاتف · سيارة — خلال 30 يوما.",
            "insights.cue_latency.title" to "زمن استجابة التعليمات P50 / P95",
            "insights.cue_latency.desc" to "من عبور العتبة لبدء الصوت. فحص مسار الصوت.",
            "insights.landmark_vs_metric.title" to "معالم مقابل متر",
            "insights.landmark_vs_metric.desc" to "جودة الصياغة — هل قلنا عند المسجد أم فقط بعد 247 م؟",
            "summary.complete" to "اكتملت الرحلة",
            "summary.unit_km" to "كم مقطوعة",
            "summary.unit_min" to "دقيقة",
            "summary.unit_kmh" to "كم/س متوسط",
            "summary.unit_mi" to "ميل مقطوعة",
            "summary.unit_mph" to "ميل/س متوسط",
            "summary.plan_another_cta" to "خطط رحلة أخرى",
            "summary.fallback_label" to "رحلة",
            "onboarding.skip" to "تخطي",
            "onboarding.next" to "التالي",
            "onboarding.start" to "لنبدأ",
            "onboarding.p1.title" to "عيناك على الطريق\nلا على الشاشة",
            "onboarding.p1.body" to "سكوفا تتحدث بالمعالم كما يفعل السكان المحليون — 'المخرج الثالث في الميدان'، 'بعد المسجد' — لتسير دون النظر إلى الشاشة.",
            "onboarding.p1.demo.phase" to "التالي",
            "onboarding.p1.demo.verb" to "المخرج الثالث",
            "onboarding.p1.demo.anchor" to "في ميدان التحرير، إلى شارع رمسيس",
            "onboarding.p2.title" to "لهجتك،\nطريقتك",
            "onboarding.p2.body" to "تعليمات بـ 7 لغات — مصرية، فصحى، إنجليزية، فرنسية، ألمانية، إسبانية، تركية. النغمة كما يتحدث الناس فعلا.",
            "onboarding.p3.title" to "تتكيف مع\nطريقة تنقلك",
            "onboarding.p3.body" to "مشاة، عداء، دراج، سكوتر، سائق، مراسل. تختار سكوفا المسار والتوقيت والنغمة المناسبة — وتتغير من رحلة لأخرى.",
            "settings.replay_tour" to "كيف تعمل سكوفا؟",
            "settings.replay_tour.desc" to "إعادة عرض الجولة التعريفية في أي وقت.",
        ),
    )

    /** Resolve a key in the requested locale. Falls back to en, then to
     *  the key itself if undefined. */
    fun t(key: String, locale: String): String {
        val direct = tables[locale]?.get(key)
        if (direct != null) return direct
        val base = locale.substringBefore('-')
        val byBase = tables[base]?.get(key)
        if (byBase != null) return byBase
        return tables["en"]?.get(key) ?: key
    }

    /** Variant with `{placeholder}` substitution. */
    fun t(key: String, locale: String, vararg subs: Pair<String, String>): String {
        var s = t(key, locale)
        for ((k, v) in subs) s = s.replace("{$k}", v)
        return s
    }

    /** True when the locale flows right-to-left. Used to set
     *  [LocalLayoutDirection] in the app's root composition. */
    fun isRtl(locale: String): Boolean = locale.startsWith("ar") || locale.startsWith("he") || locale.startsWith("fa")

    /** Layout direction enum for a locale — pass to
     *  `CompositionLocalProvider(LocalLayoutDirection provides ...)`. */
    fun layoutDirection(locale: String): LayoutDirection =
        if (isRtl(locale)) LayoutDirection.Rtl else LayoutDirection.Ltr
}

/** A composition-local copy of the active locale tag so anywhere in the
 *  tree can call `Strings.t(key, LocalLocale.current)` without threading
 *  it through every parameter. Set once at the top of `setContent`. */
val LocalLocale = compositionLocalOf { "en-US" }

/** Convenience composable lookup. */
@Composable
fun rideString(key: String): String = Strings.t(key, LocalLocale.current)

/** Convenience composable lookup with substitution. */
@Composable
fun rideString(key: String, vararg subs: Pair<String, String>): String =
    Strings.t(key, LocalLocale.current, *subs)
