package com.scoova.navlayer.core

/**
 * Typed event captured by a simulated ride. Sealed so host apps can
 * pattern-match without runtime casts.
 *
 * [tsMs] is **ride-relative** (milliseconds since the sim started),
 * not wall-clock. Makes report comparisons portable across runs.
 */
public sealed class SimEvent {
    public abstract val tsMs: Long

    /**
     * The current-instruction StateFlow ticked with a new banner
     * payload. [phase] is the firing tier (Far / Mid / Near) used by
     * cue threshold logic.
     */
    public data class Banner(
        override val tsMs: Long,
        public val maneuverIndex: Int,
        public val metersToManeuver: Double,
        public val verb: String?,
        public val anchor: String?,
        public val phase: String,
    ) : SimEvent()

    /** A voice utterance was successfully spoken (or queued). */
    public data class Voice(
        override val tsMs: Long,
        public val text: String,
        public val tone: String,
        public val spatialPan: Float = 0f,
    ) : SimEvent()
}

/**
 * Diagnostic snapshot of a finished simulation run. Generated by
 * [SimulationReport.from] from the captured [SimEvent] log + the
 * canonical maneuver list the sim was driving.
 *
 * Useful both as a developer / QA dashboard ("did the cue fire when
 * it should have?") and as a regression fixture — the report can be
 * compared across builds to catch silent cue-timing regressions.
 */
public data class SimulationReport(
    public val routeDistanceMeters: Double,
    public val durationMs: Long,
    public val maneuverCount: Int,
    public val voiceCueCount: Int,
    public val bannerUpdateCount: Int,
    /** Per-maneuver breakdown of which phases fired and at what
     *  meters-to-maneuver. */
    public val maneuvers: List<ManeuverReport>,
    /** Voice cues whose firing distance landed outside the configured
     *  threshold band for their phase — the human-readable "errors"
     *  list a developer would scroll to first. */
    public val anomalies: List<String>,
) {
    public data class ManeuverReport(
        public val index: Int,
        public val type: String,
        public val verb: String?,
        public val cuesFired: List<CueFiring>,
    )
    public data class CueFiring(
        public val phase: String,
        public val metersToManeuver: Double,
        public val voiceText: String?,
    )

    public companion object {
        /**
         * Distil a raw event log into a report. [maneuvers] is the
         * route's maneuver list used during the sim; [thresholds] is
         * the cue threshold band used by the nav engine
         * (e.g. `intArrayOf(300, 100, 30)` for Far / Mid / Near).
         */
        @JvmStatic
        public fun from(
            log: List<SimEvent>,
            maneuvers: List<ManeuverEvent>,
            thresholds: IntArray,
            routeDistanceMeters: Double,
        ): SimulationReport {
            val durationMs = log.maxOfOrNull { it.tsMs } ?: 0L
            val banners = log.filterIsInstance<SimEvent.Banner>()
            val voices = log.filterIsInstance<SimEvent.Voice>()
            val anomalies = mutableListOf<String>()

            // Group banner events by maneuver index, pick the FIRST
            // banner per phase (Far/Mid/Near) — that's when the cue
            // tripped. Multiple banners in the same phase as the
            // rider closes in are normal (meters tick down); the
            // first one is what the threshold logic chose.
            val byManeuver = banners.groupBy { it.maneuverIndex }
            val maneuverReports = maneuvers.map { m ->
                val list = byManeuver[m.index] ?: emptyList()
                val firstByPhase = list.distinctBy { it.phase }.sortedBy { it.tsMs }
                val firings = firstByPhase.map { b ->
                    // Pair with the closest voice cue in time (within
                    // 2 s of the banner update) for "this is what
                    // the rider heard for this phase". Not always
                    // there — banner may have updated without a voice.
                    val voice = voices.firstOrNull {
                        kotlin.math.abs(it.tsMs - b.tsMs) < 2_000L
                    }
                    CueFiring(
                        phase = b.phase,
                        metersToManeuver = b.metersToManeuver,
                        voiceText = voice?.text,
                    )
                }
                // Threshold-tier checks: each firing's metersToManeuver
                // should sit inside the band for its phase. Far tier
                // = [thresholds[0]..2 * thresholds[0]]; Mid = [thresholds[1]..thresholds[0]];
                // Near = [0..thresholds[2]]. Anomalies for any firing
                // outside its expected band.
                val sortedThresholds = thresholds.sortedArray()
                firings.forEach { f ->
                    val expected = expectedBand(f.phase, sortedThresholds)
                    if (expected != null && f.metersToManeuver !in expected) {
                        anomalies += "Maneuver ${m.index} ${f.phase} fired at " +
                            "${f.metersToManeuver.toInt()} m (expected ${expected.start.toInt()}–${expected.endInclusive.toInt()} m)"
                    }
                }
                ManeuverReport(
                    index = m.index,
                    type = m.type.name,
                    verb = m.bannerVerb,
                    cuesFired = firings,
                )
            }

            // Welcome repetition is a known pain point: more than one
            // "let's go"-style early-trip cue is a regression worth
            // flagging.
            val earlyCues = voices.filter { it.tsMs < 5_000L }
            if (earlyCues.size > 1) {
                anomalies += "${earlyCues.size} voice cues fired in the first 5 s — possible welcome-replay regression"
            }

            return SimulationReport(
                routeDistanceMeters = routeDistanceMeters,
                durationMs = durationMs,
                maneuverCount = maneuvers.size,
                voiceCueCount = voices.size,
                bannerUpdateCount = banners.size,
                maneuvers = maneuverReports,
                anomalies = anomalies,
            )
        }

        private fun expectedBand(phase: String, sortedThresholds: IntArray): ClosedRange<Double>? {
            if (sortedThresholds.isEmpty()) return null
            val near = sortedThresholds[0].toDouble()
            val mid = sortedThresholds.getOrNull(1)?.toDouble() ?: near
            val far = sortedThresholds.getOrNull(2)?.toDouble() ?: mid
            return when (phase.lowercase()) {
                "near" -> 0.0..near
                "mid"  -> near..mid
                "far"  -> mid..(far * 2.0)  // upper bound = 2× far gives slack for first sighting
                else   -> null
            }
        }
    }
}
